### ISSUE TITLE
JAXA worldwide data possibly better than NASA

### ISSUE THREAD

**Issue by atorger** [lukey78/open-elevation-data#1]
I have heard/read (don't remember exactly where) that the Japan Aerospace Exploration Agency worldwide elevation data released a few years ago is of better quality than the commonly used NASA data. I have no personal knowledge about this though, but I thought I could file an issue just as an heads up.

Here's the JAXA press release about the data:

https://global.jaxa.jp/press/2015/05/20150518_daichi.html

And here's a link to the website where you can get an account to download the data:
https://www.eorc.jaxa.jp/ALOS/en/aw3d30/index.htm

It seems like JAXA is actively updating the dataset, version 3.2 was released 2021

**Comment by lukey78** [comment]
That's really interesting, didn't hear about that yet. The last time I really dived into the elevation data thing was > 1 year ago. Seems also the worldwide models are going to be better.

I will try that in the next weeks or months. Especially the Himalaya region has many holes and distortions in the SRTM or NASADEM versions.

**Comment by lukey78** [comment]
I downloaded all the data yesterday - and updated this repo with information for the scripted bulk download of the 140 GB data.

I will try to generate some elevation models with the new data and compare it with the NASADEM or other sources. Help wanted! Some images with comparison shots would be nice.
